### ISSUE TITLE
Support different files with the same name

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/audiostream#6]
Currently, there is no file structure preservation or unique id's for songs, so if two songs with the same filename are requested, the second cannot be placed in library/
A file manager class, or separate process might be nice.

**Comment by nickdesaulniers** [comment]
@englercj pointed out that passing user input to a shell command is a bad idea, especially since we want this to be accessible outside our home network.  I think a rewrite is in order.

Instead of having the library/ dir as a kind of cache for files and searching for files otherwise, I think it would be better to first index all files listed in config/config.json (before starting the server), keeping track of songs by id in a lightweight db like sqlite or mongodb, then using the index to perform look up, transcode if needed, drop the transcoded version in something like a cache/ dir, add to index, and serve.  iTunes keeps a kind of cache like this as a Library.xml file:

```
Mac OS X
/Users/Your Username/Music/iTunes/iTunes Music Library.xml

Windows XP
C:\Documents and Settings\Your Username\My Documents\My Music\iTunes\iTunes Music Library.xml

Windows Vista/7
C:\Users\Your Username\Music\iTunes\iTunes Music Library.xml
```

So I think emulating this behavior, minus the XML, would be useful.

**Comment by englercj** [comment]
How about you throw the media file and metadata into a [Riak](http://docs.basho.com/riak/latest/), or [BigCouch](http://bigcouch.cloudant.com/) cluster. That way the files are not only highly available, you can map reduce through them, and not have to manage the files on disk.

You can do transcoding when the file is being stored instead of retrieved, since the user expects the storage to take some time; but the user will "want the file now" when trying to listen.

Or is the purpose of this project so the user can use this on his desktop, as opposed to a site where your media is in the cloud?

**Comment by nickdesaulniers** [comment]
I want to be able to have my own personal cloud.  Turn my linux box on and let it run.  Have access to my music wherever I go.  Any device, any browser.  So part of the problem with transcoding it before it's requested, is that unless you tanscode it so that you have mp3 and ogg versions, you don't know what the client device will support and you'll be taking up extra space.

So I was thinking personal cloud, since I don't have space on any of my machines to offer a publicly available service.

**Comment by englercj** [comment]
I'm not against a personal cloud paradigm, and I think building the storage to be pluggable would be best.

What I think would be really cool, is building this as open source and offering  a paid service for us to host your media. The service being similar to Google Music, or Amazon Cloud Player (though i have issues with both, which is why I think it would be cool to "roll our own"); but since it is open source nothing is stopping you from grabbing the source and throwing it on your own machine.

In the short-term I can throw up some VMs on my farm to handle a beta amount of traffic.

**Comment by nickdesaulniers** [comment]
That's a brilliant idea, I just have to wrap my head around what we need to change in the architecture to allow for both.  But having a single repo that works, and offering hosting is brilliant.

**Comment by englercj** [comment]
The more modularized the design is, the better. To pull an example FreeSWITCH can be deployed on an embedded system (like a router, or cell phone) or clustered across hundreds of servers. The reason it can do that is nearly _every single feature_ that isn't absolutely core to the operation of FreeSWITCH is a module that can be loaded or unloaded at will.

Making a good module load/unload framework will not only open us up to the world of user submitted modules and plugins, it will give us the ability to have a stripped down system for small deployments which can also scale up to the large enterprise level deployments.

Just food for thought :)

Also, sorry for totally hijacking this thread :P

**Comment by nickdesaulniers** [comment]
Move this conversation to the FB page.

**Comment by nickdesaulniers** [comment]
`$ ls -i` prints the inode, a unique identifier for a file.
http://stackoverflow.com/a/12060053/1027966

**Comment by nickdesaulniers** [comment]
solution:
https://github.com/nickdesaulniers/walkertexasranger/blob/master/find.js

**Comment by englercj** [comment]
Stop using `exec` lol

http://nodejs.org/api/fs.html#fs_fs_readdir_path_callback

**Comment by nickdesaulniers** [comment]
So the final part is almost done.  I want a transcoded dir/ (currently library/), where transcoded files live.  That way we can later implement size limits, and not relist files that are the same but with different encodings.  The solution that's coming soon is to drop the transcoded files in library/ but instead of having the previous name with new extension, they are named after the original file's inode (unique identifier) dot new extension.  This way we can look them up quickly and easily.

**Comment by nickdesaulniers** [comment]
library/
now contains files in the format:
previously transcoded file inode dot previously transcoded file transcoded ext
Example:
library/4532196.ogg
is a transcoded version of
/Users/wangstabill/Downloads/A Perfect Circle (Thirteenth Step)/12 Gravity.mp3
